// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/biometric" | "/dashboard-platform" | "/dashboard-platform/login" | "/modules" | "/privacy" | "/register" | "/super-admin" | "/terms"
type AppRouteHandlerRoutes = "/api/auth/check-phone" | "/api/auth/login-password" | "/api/auth/me" | "/api/auth/register-full" | "/api/auth/send-code" | "/api/billing/subscriptions" | "/api/billing/tariffs" | "/api/chat/message" | "/api/tenants/me"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard-platform" | "/super-admin"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/api/auth/check-phone": {}
  "/api/auth/login-password": {}
  "/api/auth/me": {}
  "/api/auth/register-full": {}
  "/api/auth/send-code": {}
  "/api/billing/subscriptions": {}
  "/api/billing/tariffs": {}
  "/api/chat/message": {}
  "/api/tenants/me": {}
  "/biometric": {}
  "/dashboard-platform": {}
  "/dashboard-platform/login": {}
  "/modules": {}
  "/privacy": {}
  "/register": {}
  "/super-admin": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard-platform": never
  "/super-admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
