"""Initial migration - all models

Revision ID: ca5d2b0eba52
Revises: 
Create Date: 2025-11-17 00:44:02.487173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca5d2b0eba52'
down_revision = None
branch_labels = None
depends_on = None


def table_exists(table_name: str) -> bool:
    """Check if table exists in database"""
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Initial migration: create all tables if they don't exist
    # This migration is safe to run on existing databases
    # If tables already exist, they will be skipped
    # Note: For existing databases, consider using: alembic stamp head
    
    # Create modules_registry table
    if not table_exists('modules_registry'):
        op.create_table('modules_registry',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('module_id', sa.Text(), nullable=False),
        sa.Column('version', sa.Text(), nullable=False),
        sa.Column('path', sa.Text(), nullable=False),
        sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('module_id')
        )
    
    # Create tenants table
    if not table_exists('tenants'):
        op.create_table('tenants',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('owner_phone', sa.String(length=20), nullable=False),
        sa.Column('plan', sa.Text(), nullable=True),
        sa.Column('status', sa.Text(), server_default=sa.text("'inactive'::text"), nullable=False),
        sa.Column('active_module', sa.Text(), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        postgresql_ignore_search_path=False
        )
    
    # Create users table (depends on tenants)
    if not table_exists('users'):
        op.create_table('users',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('phone', sa.String(length=20), nullable=False),
        sa.Column('phone_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('password_hash', sa.Text(), nullable=True),
        sa.Column('role', sa.Text(), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('phone')
        )
        op.create_index('idx_users_phone', 'users', ['phone'], unique=False)
        op.create_index('idx_users_role', 'users', ['role'], unique=False)
        op.create_index('idx_users_tenant_id', 'users', ['tenant_id'], unique=False)
    
    # Create subscriptions table (depends on tenants)
    if not table_exists('subscriptions'):
        op.create_table('subscriptions',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('plan', sa.Text(), nullable=True),
        sa.Column('status', sa.Text(), nullable=False),
        sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('trial_used', sa.Boolean(), server_default=sa.text('false'), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_subscriptions_tenant_id', 'subscriptions', ['tenant_id'], unique=False)
    
    # Create platform_content table (depends on users)
    if not table_exists('platform_content'):
        op.create_table('platform_content',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('key', sa.Text(), nullable=False),
        sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key')
        )
        op.create_index('idx_platform_content_key', 'platform_content', ['key'], unique=False)
    
    # Create tenant_domains table (depends on tenants)
    if not table_exists('tenant_domains'):
        op.create_table('tenant_domains',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('domain', sa.Text(), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
        sa.Column('is_frozen', sa.Boolean(), server_default=sa.text('false'), nullable=True),
        sa.Column('frozen_until', postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('domain')
        )
        op.create_index('idx_tenant_domains_tenant_id', 'tenant_domains', ['tenant_id'], unique=False)
        op.create_index('idx_tenant_domains_domain', 'tenant_domains', ['domain'], unique=False)
    
    # Create deleted_accounts_history table
    if not table_exists('deleted_accounts_history'):
        op.create_table('deleted_accounts_history',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    
    # Create audit_logs table (depends on tenants and users)
    if not table_exists('audit_logs'):
        op.create_table('audit_logs',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('action', sa.Text(), nullable=False),
        sa.Column('resource_type', sa.Text(), nullable=True),
        sa.Column('resource_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('correlation_id', sa.Text(), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_audit_logs_tenant_id', 'audit_logs', ['tenant_id'], unique=False)
        op.create_index('idx_audit_logs_correlation_id', 'audit_logs', ['correlation_id'], unique=False)
    
    # Create module_settings table
    if not table_exists('module_settings'):
        op.create_table('module_settings',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('module_id', sa.Text(), nullable=False),
        sa.Column('trial_days', sa.Integer(), server_default=sa.text('14'), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('module_id')
        )
        op.create_index('idx_module_settings_module_id', 'module_settings', ['module_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in reverse order of creation (respecting foreign keys)
    # This will DELETE ALL DATA - use with caution!
    
    if table_exists('module_settings'):
        op.drop_index('idx_module_settings_module_id', table_name='module_settings')
        op.drop_table('module_settings')
    
    if table_exists('audit_logs'):
        op.drop_index('idx_audit_logs_correlation_id', table_name='audit_logs')
        op.drop_index('idx_audit_logs_tenant_id', table_name='audit_logs')
        op.drop_table('audit_logs')
    
    if table_exists('deleted_accounts_history'):
        op.drop_table('deleted_accounts_history')
    
    if table_exists('tenant_domains'):
        op.drop_index('idx_tenant_domains_domain', table_name='tenant_domains')
        op.drop_index('idx_tenant_domains_tenant_id', table_name='tenant_domains')
        op.drop_table('tenant_domains')
    
    if table_exists('platform_content'):
        op.drop_index('idx_platform_content_key', table_name='platform_content')
        op.drop_table('platform_content')
    
    if table_exists('subscriptions'):
        op.drop_index('idx_subscriptions_tenant_id', table_name='subscriptions')
        op.drop_table('subscriptions')
    
    if table_exists('users'):
        op.drop_index('idx_users_tenant_id', table_name='users')
        op.drop_index('idx_users_role', table_name='users')
        op.drop_index('idx_users_phone', table_name='users')
        op.drop_table('users')
    
    if table_exists('tenants'):
        op.drop_table('tenants')
    
    if table_exists('modules_registry'):
        op.drop_table('modules_registry')
    # ### end Alembic commands ###
